// Generated by CoffeeScript 1.7.1
(function() {
  var ansi, date_format, log, logDate, moment, static_exts, util, _,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  moment = require('moment');

  _ = require('underscore');

  util = require('util');

  ansi = require('ansi')(process.stdout);

  date_format = 'YYYY-MM-DD hh:mm:ss';

  logDate = function() {
    ansi.grey();
    ansi.write('[' + moment().format(date_format) + '] ');
    return ansi.reset();
  };

  exports.log = log = function(s, options) {
    if (options == null) {
      options = {};
    }
    if ((options.date == null) || options.date) {
      logDate();
    }
    if (options.hex != null) {
      ansi.hex(options.hex);
    }
    if (options.color != null) {
      ansi.fg[options.color]();
    }
    ansi.write(s + '\n');
    return ansi.reset();
  };

  log.w = function(s) {
    return log(s, {
      color: 'yellow'
    });
  };

  log.i = function(s) {
    return log(s, {
      color: 'cyan'
    });
  };

  log.e = function(s) {
    return log(s, {
      color: 'red'
    });
  };

  log.d = function(s) {
    return log(s, {
      color: 'grey'
    });
  };

  log.s = function(s) {
    return log(s, {
      color: 'green'
    });
  };

  static_exts = ['css', 'js', 'jpg', 'png', 'gif', 'woff', 'svg'];

  exports.is_static_url = function(url) {
    var _ref;
    return _ref = url.split('.').slice(-1)[0], __indexOf.call(static_exts, _ref) >= 0;
  };

  exports.capitalize = function(type) {
    return type[0].toUpperCase() + type.slice(1);
  };

  exports.randomString = function(len) {
    var s;
    if (len == null) {
      len = 8;
    }
    s = '';
    while (s.length < len) {
      s += Math.random().toString(36).slice(2, len - s.length + 2);
    }
    return s;
  };

  exports.randomChoice = function(l) {
    return l[Math.floor(Math.random() * l.length)];
  };

  exports.serviceSummary = function(service) {
    return service.name + '@' + service.binding.host + ':' + service.binding.port;
  };

  exports.makeAddress = function(host, port) {
    return 'tcp://' + host + ':' + port;
  };

  exports.randomPort = function() {
    return 10000 + Math.floor(Math.random() * 50000);
  };

  exports.makeBindingAddress = function(protocol, port) {
    return protocol + '://0.0.0.0:' + port;
  };

}).call(this);
