// Generated by CoffeeScript 1.10.0
(function() {
  var add, avg, client, dts, sendHello, sendHellos, somata, sum;

  somata = require('.');

  client = new somata.Client;

  add = function(a, b) {
    return a + b;
  };

  sum = function(l) {
    return l.reduce(add, 0);
  };

  avg = function(l) {
    return sum(l) / l.length;
  };

  dts = [];

  sendHello = function(cb) {
    return client.remote('hello', 'sayHello', 'world', cb);
  };

  sendHellos = function() {
    var n, n_hellos, saidHello, start_t;
    n_hellos = 1;
    n = n_hellos;
    start_t = new Date().getTime();
    saidHello = function(err, hello) {
      var dt, end_t;
      if (err != null) {
        end_t = new Date().getTime();
        dt = (end_t - start_t) / 1000;
        return console.log("[" + (n_hellos - n) + "] Failed after " + dt);
      } else if (n > 0) {
        n -= 1;
        return sendHello(saidHello);
      } else {
        end_t = new Date().getTime();
        dt = (end_t - start_t) / 1000;
        dts.push(dt);
        return console.log("[" + n_hellos + "] Done after " + dt + " avg " + (avg(dts)));
      }
    };
    return sendHello(saidHello);
  };

  setInterval(sendHellos, 5000);

  sendHellos();

}).call(this);
