// Generated by CoffeeScript 2.4.1
var EventEmitter, Subscription, debug;

EventEmitter = require('events');

debug = require('debug')('somata:subscription');

module.exports = Subscription = class Subscription {
  constructor() {
    this.emitter = new EventEmitter;
  }

  on() {
    return this.emitter.on(...arguments);
  }

  emit() {
    return this.emitter.emit(...arguments);
  }

};
