// Generated by CoffeeScript 1.12.4
var ConsulAgent, agent, test_service, util;

ConsulAgent = require('../consul-agent');

util = require('util');

test_service = {
  Name: 'testing',
  Port: 4382
};

agent = new ConsulAgent;

agent.registerService(test_service, function(err, registered) {
  console.log('Registered.');
  return agent.getServices(function(err, services) {
    console.log('Services: ' + util.inspect(services));
    return agent.getServiceNodes(test_service.Name, function(err, nodes) {
      console.log('Nodes: ' + util.inspect(nodes));
      return agent.deregisterService(test_service.Name, function(err, deregistered) {
        console.log('Deregistered.');
        return agent.getServices(function(err, services) {
          return console.log('Services: ' + util.inspect(services));
        });
      });
    });
  });
});
